name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
      IMAGE_NAME: avatarbot
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: docker build . --tag $IMAGE_NAME:$GITHUB_SHA
    - name: stop
      run: docker rm -f $IMAGE_NAME
    - name: run
      run: docker run -d -p 5656:80 --network=apps --restart=always --env BOT_TOKEN=$BOT_TOKEN --name $IMAGE_NAME $IMAGE_NAME:$GITHUB_SHA
    - name: cleanup docker containers
      run: docker container prune --filter "until=30m" -f
    - name: cleanup docker images
      run: docker image prune -a -f --filter "until=30m"
